---

# Does not work yet. Some Ruby dependency thing that I was not able to solve.
language: ruby

install:
  # install Java 8 as required by vnu.jar
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -qq oracle-java8-installer'
  - 'sudo update-java-alternatives -s java-8-oracle'
  ## https://travis-ci.org/debops/debops.github.io/builds/291139495
  - 'gem install RedCloth -v 4.2.9'
  - 'gem install jekyll html-proofer jekyll-sitemap'
  - 'sudo pip install html5validator'

script:
  - 'make check'
